# Setup
title:               Tianyu Shi
tagline:             'Blogs'
description:         Only the Paramoid Survive.
url:                 https://sty-hhh.github.io
baseurl:             ''
paginate:            5
paginate_path:       '/blogs/page:num'
permalink:           pretty
timezone:            Asia/Shanghai

# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Gems
plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed

version:             1.0

minima:
  date_format: "%b %-d, %Y"

theme: minima